project:
  type: website
  output-dir: ./_html

website:
  title: "iBridges GUI"
  navbar:
    title: false
    logo: docs/screenshots/logo.png
    left:
      - href: index.qmd
        text: Home
      - href: docs/info.qmd
        text: What is iBridges-Gui?
      - href: docs/getting-started.qmd
        text: Getting started
      - href: docs/userdoc.qmd
        text: Documentation
      - href: docs/developers.qmd
        text: Contributing to iBridges
      - href: docs/faq.qmd
        text: FAQ
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/iBridges-for-iRODS/iBridges-GUI
          - text: Report and Issue
            url: https://github.com/iBridges-for-iRODS/iBridges-GUI/issues
    repo-actions: [edit, issue, source]

format:
  html:
    theme: flatly
    css: 
      - _styles/ibridges.css
      - _styles/hyperlinks.css
      - _styles/toc.css
      - _styles/callouts.css
      - _styles/code.css
      - _styles/navbar.css
      - _styles/search_icon.css
    toc: true
