"""Pipeline to create pyinstaller executables.

The --onefile option is not used because Windows must upack the
executable before it can run.  This makes it roughly 30 seconds
slower than the current variant.
"""
from datetime import datetime
import xml.etree.ElementTree as ET
import platform
import subprocess
import utils

ICON_VAR = 'icon'
TAB_LEN = 4
TAB = ' ' * TAB_LEN
PIXMAP_STR = '.addPixmap(QtGui.QPixmap('
DEBUG_MODE = False


def run_cmd(command: str, pass_error: bool = False):
    """Run command in shell, stdout is printed to the screen

    Parameters
    ----------
    command : str
        Input shell command line.
    pass_error : bool
        Exit or pass on error
    """
    proc = subprocess.run(command, stderr=subprocess.PIPE, stdout=subprocess.PIPE, shell=True,
                          universal_newlines=True)
    # Print all errors
    if proc.stderr != '':
        print(f'commandline error: {proc.stderr}')
        if pass_error == False:
            raise Exception('shell run error')
    return proc.stdout


def ui_to_py(dirname: str, py_exec: str):
    """Convert the .ui files to .py files

    Parameters
    ----------
    dirname : str
        Name of directory holding UI files.
    py_exec : str
        Name of Python executable.  It should be the full path if not
        in PATH.

    The command-line takes the form:
        python -m PyQt6.uic.pyuic -x file.ui -o file.py

    """
    for uipath in sorted(utils.path.LocalPath(dirname).glob('*.ui')):
        basename = uipath.stem
        pypath = utils.path.LocalPath(dirname, f'{basename}.py')
        print(f'Converting {uipath} to {pypath}')
        run_cmd(f'{py_exec} -m PyQt6.uic.pyuic -x {uipath} -o {pypath}')
        # Find and replace the pixelmap references.  They are hardcoded.
        # Also have to go up one directory for the executable, it's ugly!
        inlines = pypath.read_text()
        outlines = [
            '"""Created by: PyQt6 UI code generator from the corresponding UI file',
            '',
            'WARNING: Any manual changes made to this file will be lost when pyuic6 is',
            'run again.  Do not edit this file unless you know what you are doing.',
            '"""',
        ]
        if PIXMAP_STR in inlines:
            for inline in inlines.split('\n'):
                if PIXMAP_STR not in inline:
                    outlines.append(inline)
                else:
                    first, icon_path, last = inline.split('"')
                    icon_path = icon_path.split("..")[-1]
                    outlines.append(
                        f'{first}r"..{utils.path.LocalPath(icon_path)}"{last}')
        else:
            outlines.extend(inlines.split('\n'))
        pypath.write_text(
            '\n'.join(line for line in outlines if not line.startswith('#')))


def cleanup_prev_build(distpath: str, ibridgedistpath: str):
    """Cleanup the dist/iBridges.dist folders from previous builds. 
    Parameters
    ----------
    distpath : str
        Name of pyinstaller output folder
    ibridgedistpath : str
        Name of the Nuitka output folder
    """
    if distpath.exists():
        distpath.rmdir(squash=True)
    if ibridgedistpath.exists():
        ibridgedistpath.rmdir(squash=True)


def remove_pyui_files(dirname: str):
    """Remove the locally stored Python versions of the UI files.

    Parameters
    ----------
    dirname : str
        Name of directory holding UI files.

    """
    for pypath in sorted(utils.path.LocalPath(dirname).glob('*.py')):
        if '__init__.py' not in pypath:
            print(f'Removing {pypath}')
            pypath.unlink()


def replace_directory(source: str, destination: str):
    """Overwrite `destination` with a copy of all contents of `source`.

    Parameters
    ----------
    source : str
        Name of source directory.
    destination : str
        Name of destination directory.

    """
    utils.path.LocalPath(source).copy_path(destination, squash=True)


def QT_ifw_installed(qt_ifwpath):
    """Check if QT installer framework is available 

    Parameters
    ----------
    qt_ifwpath : str
        Installation directory

    Returns
    -------
    boolean

    """
    try:
        if ('win' in platform.platform().lower() and qt_ifwpath.joinpath('binarycreator.exe').exists()):
            return True
        return (subprocess.call(['which', 'binarycreator']) == 0)
    except Exception as error:
        return False


def main() -> int:
    """Main function.

    Indicates (along with if __name__ == '__main__':) a Python script.

    "compile" UI files into Python files so they can be imported
    directly, creating a virtual environment if necessary prior to
    creating a PyInstaller distribution package.

    Returns
    -------
    int
        Exit code of the program.

    """
    buildtool = "nuitka"
    relpath = utils.path.LocalPath('.')
    iconpath = relpath.joinpath('gui', 'icons')
    uipath = relpath.joinpath('gui', 'ui_files')
    venvpath = relpath.joinpath('venv')
    distpath = relpath.joinpath('dist')
    ibridgedistpath = relpath.joinpath('iBridges.dist')
    installerpath = relpath.joinpath('installer')
    qt_ifwpath = utils.path.LocalPath('C:/Qt/QtIFW-4.6.0/bin')

    cleanup_prev_build(distpath, ibridgedistpath)
    confirmation = input("Do you want to build with nuitka (default) pyinstaller (py)?")
    if (len(confirmation) > 0) and confirmation[0].upper().startswith('PY'):
        buildtool = "pyinstaller"
    # Step 1: Convert .ui files to .py files after first removing .py
    # files that already exist.  Recompiling is the best way to ensure
    # they are up-to-date.
    try:
        remove_pyui_files(uipath)
        ui_to_py(uipath, 'python')
    except Exception as error:
        print(f'Error converting UI files to Python: {error}')
        return 1
    # Step 2: The buildtools includes all dependencies in the environment,
    # a venv is created to minimize the overhead.
    try:
        venvpath.mkdir(exist_ok=True)
        if utils.path.is_posix():
            venv_script = venvpath.joinpath('bin', 'activate')
            venv_activate = f'source {venv_script}'
        else:
            venv_script = venvpath.joinpath("Scripts", "activate.bat")
            venv_activate = str(venv_script)
        # Create the venv if needed.
        if not venv_script.is_file():
            run_cmd(f'python -m venv {venvpath}')
            run_cmd(f'{venv_activate} && python -m pip install --upgrade pip')
            run_cmd(f'{venv_activate} && pip3 install -r requirements.txt')
    except Exception as error:
        print(f'Error finding/creating virtual environment: {error}')
        return 2
    # Step 3: Activate venv and run pyinstaller/nuitka.
    filenames = f'{iconpath.joinpath("iBridges.ico")} iBridges.py'
    try:
        if buildtool == "nuitka":
            cmd = f"{venv_activate} && python -m nuitka "
            if DEBUG_MODE is False:
                cmd += "--disable-console "
            run_cmd(f'{cmd} --standalone \
                --remove-output --enable-plugin=pyqt6 --include-qt-plugins=sensible,styles \
                --assume-yes-for-downloads --show-progress --quiet \
                --nofollow-import-to=tkinter \
                --windows-icon-from-ico={filenames}', True)
        elif buildtool == "pyinstaller":
            run_cmd(f'{venv_activate} && pyinstaller --clean --noconfirm --icon {filenames}')
        else:
            print('unknown buildtoold:', buildtool)
    except Exception as error:
        print(f'Error creating executable: {error}')
        return 3
    # Optional post-installer actions.
    if buildtool == "pyinstaller":
        confirmation = input("Do you want to cleanup the build environment (Y/N): ")
        if (len(confirmation) > 0) and (confirmation[0].upper().startswith('Y')):
            try:
                relpath.joinpath('build').rmdir(squash=True)
                relpath.joinpath('iBridges.spec').unlink()
            except Exception as error:
                print(f'Error cleaning up: {error}')
                return 4
    
    # Check if QT installer framework is available 
    # On windows binarycreator was not added to the path
    # Create QT installation framework installer
    confirmation = input("Do you want to create an installer? (Y/N): ")
    if QT_ifw_installed(qt_ifwpath) and (len(confirmation) > 0) and (confirmation[0].upper().startswith('Y')):
        # Step 4: Create the folders: data, icon & meta
        data_ipath = installerpath.joinpath('dist', 'data')
        icons_ipath = installerpath.joinpath('dist', 'icon')
        meta_ipath = installerpath.joinpath('dist', 'meta')
        data_ipath.mkdir(parents=True, exist_ok=True)
        icons_ipath.mkdir(parents=True, exist_ok=True)
        meta_ipath.mkdir(parents=True, exist_ok=True)

        # Step 5: Copy icons, license, config files & code to the right folders
        try:
            if buildtool == "nuitka":
                ibridgedistpath.replace_path(data_ipath, True)
            else:
                distpath.replace_path(data_ipath, True)
            dist_icons = data_ipath.joinpath('icons')
            replace_directory(iconpath, dist_icons)
            (iconpath.joinpath('iBridges.ico')).copy_path(icons_ipath.joinpath('icon.ico'), squash=True)
            (relpath.joinpath('LICENSE')).copy_path(meta_ipath.joinpath('license.txt'), squash=True)
            (installerpath.joinpath('installerscript.qs')).copy_path(meta_ipath.joinpath('installerscript.qs'),
                                                                     squash=True)
            (installerpath.joinpath('package.xml')).copy_path(meta_ipath.joinpath('package.xml'), squash=True)
        except Exception as error:
            print(f'Error copying files to installer folders: {error}')
            return 5
        
        # step 6: Update the config
        package_xml = ET.parse(meta_ipath.joinpath('package.xml'))
        release_date = package_xml.find("ReleaseDate")
        release_date.text = datetime.now().strftime("%Y-%m-%d")
        code_version = run_cmd('git describe --tag', True).strip()
        if code_version != '':
            version = package_xml.find("Version")
            version.text = code_version
        package_xml.write(meta_ipath.joinpath('package.xml'))

        # Step 7: Create installer
        try:
            cmd = f" cd {installerpath} && \
            {qt_ifwpath.joinpath('binarycreator.exe')} --offline-only \
            -t {qt_ifwpath.joinpath('installerbase.exe')} -p . \
            -c config.xml iBridges_installer.exe"
            print(cmd)
            run_cmd(cmd)
        except Exception as error:
            print(f'Error creating installer: {error}')
            return 6
    return 0


if __name__ == '__main__':
    exit(main())
