# Form implementation generated from reading ui file 'ibridgesgui/ui_files/MainMenu.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1300, 850)
        MainWindow.setMinimumSize(QtCore.QSize(1300, 850))
        MainWindow.setStyleSheet("QWidget\n"
"{\n"
"    color: rgb(86, 184, 139);\n"
"    background-color: rgb(54, 54, 54);\n"
"    selection-background-color: rgb(58, 152, 112);\n"
"    font: 16pt;\n"
"}\n"
"\n"
"QTabBar::tab:top:selected {\n"
"    background-color: rgb(58, 152, 112);\n"
"    color: rgb(54, 54, 54);\n"
"}\n"
"\n"
"QLabel#error_label\n"
"{\n"
"    color: rgb(217, 174, 23);\n"
"     font: 18pt;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_widget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tab_widget.setMinimumSize(QtCore.QSize(600, 300))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        self.tab_widget.setFont(font)
        self.tab_widget.setObjectName("tab_widget")
        self.verticalLayout.addWidget(self.tab_widget)
        self.error_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.verticalLayout.addWidget(self.error_label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1300, 24))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.main_menu = QtWidgets.QMenu(parent=self.menubar)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        self.main_menu.setFont(font)
        self.main_menu.setObjectName("main_menu")
        self.config_menu = QtWidgets.QMenu(parent=self.menubar)
        self.config_menu.setObjectName("config_menu")
        MainWindow.setMenuBar(self.menubar)
        self.action_close_session = QtGui.QAction(parent=MainWindow)
        font = QtGui.QFont()
        self.action_close_session.setFont(font)
        self.action_close_session.setObjectName("action_close_session")
        self.action_exit = QtGui.QAction(parent=MainWindow)
        font = QtGui.QFont()
        self.action_exit.setFont(font)
        self.action_exit.setObjectName("action_exit")
        self.actionSearch = QtGui.QAction(parent=MainWindow)
        font = QtGui.QFont()
        self.actionSearch.setFont(font)
        self.actionSearch.setObjectName("actionSearch")
        self.actionSaveConfig = QtGui.QAction(parent=MainWindow)
        font = QtGui.QFont()
        self.actionSaveConfig.setFont(font)
        self.actionSaveConfig.setObjectName("actionSaveConfig")
        self.action_connect = QtGui.QAction(parent=MainWindow)
        self.action_connect.setObjectName("action_connect")
        self.action_check_configuration = QtGui.QAction(parent=MainWindow)
        self.action_check_configuration.setObjectName("action_check_configuration")
        self.action_add_configuration = QtGui.QAction(parent=MainWindow)
        self.action_add_configuration.setObjectName("action_add_configuration")
        self.main_menu.addAction(self.action_connect)
        self.main_menu.addAction(self.action_close_session)
        self.main_menu.addAction(self.action_exit)
        self.config_menu.addAction(self.action_check_configuration)
        self.config_menu.addAction(self.action_add_configuration)
        self.menubar.addAction(self.main_menu.menuAction())
        self.menubar.addAction(self.config_menu.menuAction())

        self.retranslateUi(MainWindow)
        self.tab_widget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.main_menu.setTitle(_translate("MainWindow", "Connect"))
        self.config_menu.setTitle(_translate("MainWindow", "Configure"))
        self.action_close_session.setText(_translate("MainWindow", "Close Connection"))
        self.action_exit.setText(_translate("MainWindow", "Exit iBridges"))
        self.actionSearch.setText(_translate("MainWindow", "Search"))
        self.actionSaveConfig.setText(_translate("MainWindow", "Save configuration"))
        self.action_connect.setText(_translate("MainWindow", "Connect to iRODS"))
        self.action_check_configuration.setText(_translate("MainWindow", "Check Configuration"))
        self.action_add_configuration.setText(_translate("MainWindow", "Add Configuration"))
