# Form implementation generated from reading ui file 'ibridgesgui/ui_files/configCheck.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_configCheck(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1034, 513)
        Dialog.setStyleSheet("QWidget\n"
"{\n"
"    color: rgb(86, 184, 139);\n"
"    background-color: rgb(54, 54, 54);\n"
"    font: 14pt\n"
"}\n"
"\n"
"QLabel#errorLabel\n"
"{\n"
"    color: rgb(217, 174, 23);\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.envbox = QtWidgets.QComboBox(parent=Dialog)
        self.envbox.setObjectName("envbox")
        self.horizontalLayout.addWidget(self.envbox)
        self.loadButton = QtWidgets.QPushButton(parent=Dialog)
        self.loadButton.setObjectName("loadButton")
        self.horizontalLayout.addWidget(self.loadButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.createButton = QtWidgets.QPushButton(parent=Dialog)
        self.createButton.setObjectName("createButton")
        self.horizontalLayout.addWidget(self.createButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.envEdit = QtWidgets.QTextEdit(parent=Dialog)
        self.envEdit.setObjectName("envEdit")
        self.verticalLayout.addWidget(self.envEdit)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkButton = QtWidgets.QPushButton(parent=Dialog)
        self.checkButton.setObjectName("checkButton")
        self.horizontalLayout_4.addWidget(self.checkButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.errorLabel = QtWidgets.QLabel(parent=Dialog)
        self.errorLabel.setText("")
        self.errorLabel.setObjectName("errorLabel")
        self.horizontalLayout_4.addWidget(self.errorLabel)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.saveButton = QtWidgets.QPushButton(parent=Dialog)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_2.addWidget(self.saveButton)
        self.saveasButton = QtWidgets.QPushButton(parent=Dialog)
        self.saveasButton.setObjectName("saveasButton")
        self.horizontalLayout_2.addWidget(self.saveasButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.closeButton = QtWidgets.QPushButton(parent=Dialog)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.loadButton.setText(_translate("Dialog", "Load"))
        self.createButton.setText(_translate("Dialog", "Create new"))
        self.checkButton.setText(_translate("Dialog", "Check"))
        self.saveButton.setText(_translate("Dialog", "Save"))
        self.saveasButton.setText(_translate("Dialog", "Save as"))
        self.closeButton.setText(_translate("Dialog", "Close"))
