# Form implementation generated from reading ui file 'ibridgesgui/ui_files/createCollection.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_createCollection(object):
    def setupUi(self, createCollection):
        createCollection.setObjectName("createCollection")
        createCollection.resize(500, 251)
        createCollection.setMinimumSize(QtCore.QSize(500, 200))
        createCollection.setMaximumSize(QtCore.QSize(500, 300))
        createCollection.setStyleSheet("QWidget\n"
"{\n"
"    background-color: rgb(211,211,211);\n"
"    color: rgb(88, 88, 90);\n"
"    selection-background-color: rgb(21, 165, 137);\n"
"    selection-color: rgb(245, 244, 244);\n"
"    font: 16pt\n"
"}\n"
"\n"
"QLabel#error_label\n"
"{\n"
"    color: rgb(220, 130, 30);\n"
"}\n"
"\n"
"QLineEdit, QTextEdit, QTableWidget\n"
"{\n"
"   background-color:  rgb(245, 244, 244)\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(21, 165, 137);\n"
"    color: rgb(245, 244, 244);\n"
"}\n"
"\n"
"QPushButton#home_button, QPushButton#parent_button, QPushButton#refresh_button\n"
"{\n"
"    background-color: rgb(245, 244, 244);\n"
"}\n"
"\n"
"QTabWidget#info_tabs\n"
"{\n"
"     background-color: background-color: rgb(211,211,211);\n"
"}\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(createCollection)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(parent=createCollection)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QTextBrowser(parent=createCollection)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_3 = QtWidgets.QLabel(parent=createCollection)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.coll_path_input = QtWidgets.QLineEdit(parent=createCollection)
        self.coll_path_input.setObjectName("coll_path_input")
        self.verticalLayout.addWidget(self.coll_path_input)
        self.error_label = QtWidgets.QLabel(parent=createCollection)
        self.error_label.setStyleSheet("")
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.verticalLayout.addWidget(self.error_label)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=createCollection)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(createCollection)
        self.buttonBox.accepted.connect(createCollection.accept) # type: ignore
        self.buttonBox.rejected.connect(createCollection.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(createCollection)

    def retranslateUi(self, createCollection):
        _translate = QtCore.QCoreApplication.translate
        createCollection.setWindowTitle(_translate("createCollection", "New Collection"))
        self.label_2.setText(_translate("createCollection", "Parent path:"))
        self.label_3.setText(_translate("createCollection", "New name"))
