# Form implementation generated from reading ui file 'ibridgesgui/ui_files/irodsLogin.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_irodsLogin(object):
    def setupUi(self, irodsLogin):
        irodsLogin.setObjectName("irodsLogin")
        irodsLogin.resize(770, 332)
        irodsLogin.setMinimumSize(QtCore.QSize(770, 320))
        irodsLogin.setStyleSheet("QWidget\n"
"{\n"
"    background-color: rgb(54, 54, 54);\n"
"    color: rgb(86, 184, 139);\n"
"    border-color: rgb(217, 174, 23);\n"
"    font: 16pt;\n"
"}\n"
"\n"
"QLineEdit\n"
"{\n"
"    background-color: rgb(85, 87, 83);\n"
"    border-color: rgb(217, 174, 23);\n"
"    font: 18pt;\n"
"}\n"
"\n"
"QLabel#error_label\n"
"{\n"
"    color: rgb(217, 174, 23);\n"
"     font: 18pt;\n"
"}\n"
"\n"
"QLabel#label_2\n"
"{\n"
"    font: 22pt;\n"
"    \n"
"}\n"
"\n"
"")
        self.gridLayout_2 = QtWidgets.QGridLayout(irodsLogin)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        self.envbox = QtWidgets.QComboBox(parent=irodsLogin)
        self.envbox.setObjectName("envbox")
        self.gridLayout.addWidget(self.envbox, 3, 2, 1, 2)
        self.password_field = QtWidgets.QLineEdit(parent=irodsLogin)
        self.password_field.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.password_field.setText("")
        self.password_field.setClearButtonEnabled(True)
        self.password_field.setObjectName("password_field")
        self.gridLayout.addWidget(self.password_field, 6, 2, 1, 2)
        self.label_4 = QtWidgets.QLabel(parent=irodsLogin)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=irodsLogin)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setStyleSheet("")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=irodsLogin)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_1 = QtWidgets.QLabel(parent=irodsLogin)
        self.label_1.setObjectName("label_1")
        self.gridLayout.addWidget(self.label_1, 6, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.error_label = QtWidgets.QLabel(parent=irodsLogin)
        self.error_label.setStyleSheet("")
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.horizontalLayout.addWidget(self.error_label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.cancel_button = QtWidgets.QPushButton(parent=irodsLogin)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout.addWidget(self.cancel_button)
        self.connect_button = QtWidgets.QPushButton(parent=irodsLogin)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        self.connect_button.setFont(font)
        self.connect_button.setAutoDefault(True)
        self.connect_button.setDefault(True)
        self.connect_button.setObjectName("connect_button")
        self.horizontalLayout.addWidget(self.connect_button)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 1, 1, 1)

        self.retranslateUi(irodsLogin)
        QtCore.QMetaObject.connectSlotsByName(irodsLogin)

    def retranslateUi(self, irodsLogin):
        _translate = QtCore.QCoreApplication.translate
        irodsLogin.setWindowTitle(_translate("irodsLogin", "Dialog"))
        self.label_4.setText(_translate("irodsLogin", " iRODS environment file:"))
        self.label_2.setText(_translate("irodsLogin", "iRODS Login"))
        self.label_1.setText(_translate("irodsLogin", "Password"))
        self.cancel_button.setText(_translate("irodsLogin", "Cancel"))
        self.connect_button.setText(_translate("irodsLogin", "Connect"))
