# Form implementation generated from reading ui file 'ibridgesgui/ui_files/tabInfo.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tabInfo(object):
    def setupUi(self, tabInfo):
        tabInfo.setObjectName("tabInfo")
        tabInfo.resize(640, 572)
        tabInfo.setStyleSheet("QWidget\n"
"{\n"
"    background-color: rgb(245, 244, 244);\n"
"    color: rgb(88, 88, 90);\n"
"    selection-background-color: rgb(21, 165, 137);\n"
"    selection-color: rgb(245, 244, 244)\n"
"}\n"
"\n"
"QLabel\n"
"{\n"
"  background-color: rgb(211,211,211);\n"
"}\n"
"\n"
"QLabel#error_label\n"
"{\n"
"    color: rgb(252, 152, 3);\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(21, 165, 137);\n"
"    color: rgb(245, 244, 244);\n"
"}\n"
"\n"
"QTextEdit, QTableWidget\n"
"{\n"
"     background-color: rgb(245, 244, 244)\n"
"}\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(tabInfo)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.zone_label = QtWidgets.QLabel(parent=tabInfo)
        self.zone_label.setText("")
        self.zone_label.setObjectName("zone_label")
        self.gridLayout.addWidget(self.zone_label, 3, 2, 1, 1)
        self.user_label = QtWidgets.QLabel(parent=tabInfo)
        self.user_label.setText("")
        self.user_label.setObjectName("user_label")
        self.gridLayout.addWidget(self.user_label, 4, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 13, 0, 1, 1)
        self.type_label = QtWidgets.QLabel(parent=tabInfo)
        self.type_label.setText("")
        self.type_label.setObjectName("type_label")
        self.gridLayout.addWidget(self.type_label, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=tabInfo)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 14, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.refresh_button = QtWidgets.QPushButton(parent=tabInfo)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        self.refresh_button.setFont(font)
        self.refresh_button.setObjectName("refresh_button")
        self.horizontalLayout_3.addWidget(self.refresh_button)
        self.gridLayout.addLayout(self.horizontalLayout_3, 19, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem2, 6, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(parent=tabInfo)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 15, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem3, 16, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(parent=tabInfo)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 12, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem5, 18, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(parent=tabInfo)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=tabInfo)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem6, 11, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=tabInfo)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(parent=tabInfo)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.resc_label = QtWidgets.QLabel(parent=tabInfo)
        self.resc_label.setText("")
        self.resc_label.setObjectName("resc_label")
        self.gridLayout.addWidget(self.resc_label, 8, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=tabInfo)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.resc_table = QtWidgets.QTableWidget(parent=tabInfo)
        self.resc_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.resc_table.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.resc_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.resc_table.setObjectName("resc_table")
        self.resc_table.setColumnCount(3)
        self.resc_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.resc_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.resc_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.resc_table.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.resc_table, 17, 2, 1, 1)
        self.groups_browser = QtWidgets.QTextBrowser(parent=tabInfo)
        self.groups_browser.setObjectName("groups_browser")
        self.gridLayout.addWidget(self.groups_browser, 7, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=tabInfo)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(parent=tabInfo)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 17, 0, 1, 1)
        self.version_label = QtWidgets.QLabel(parent=tabInfo)
        self.version_label.setText("")
        self.version_label.setObjectName("version_label")
        self.gridLayout.addWidget(self.version_label, 15, 2, 1, 1)
        self.log_label = QtWidgets.QLabel(parent=tabInfo)
        self.log_label.setText("")
        self.log_label.setObjectName("log_label")
        self.gridLayout.addWidget(self.log_label, 9, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=tabInfo)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 9, 0, 1, 1)
        self.server_label = QtWidgets.QLabel(parent=tabInfo)
        self.server_label.setText("")
        self.server_label.setObjectName("server_label")
        self.gridLayout.addWidget(self.server_label, 14, 2, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem7, 10, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)

        self.retranslateUi(tabInfo)
        QtCore.QMetaObject.connectSlotsByName(tabInfo)

    def retranslateUi(self, tabInfo):
        _translate = QtCore.QCoreApplication.translate
        tabInfo.setWindowTitle(_translate("tabInfo", "Form"))
        self.label_2.setText(_translate("tabInfo", "Server"))
        self.refresh_button.setText(_translate("tabInfo", "Refresh"))
        self.label_13.setText(_translate("tabInfo", "Version"))
        self.label_12.setText(_translate("tabInfo", "Server Information"))
        self.label_11.setText(_translate("tabInfo", "Client Information"))
        self.label_4.setText(_translate("tabInfo", "Username"))
        self.label_5.setText(_translate("tabInfo", "User\'s groups"))
        self.label_10.setText(_translate("tabInfo", "Usertype"))
        self.label_8.setText(_translate("tabInfo", "Default resource"))
        item = self.resc_table.horizontalHeaderItem(0)
        item.setText(_translate("tabInfo", "Name"))
        item = self.resc_table.horizontalHeaderItem(1)
        item.setText(_translate("tabInfo", "Status"))
        item = self.resc_table.horizontalHeaderItem(2)
        item.setText(_translate("tabInfo", "Free Space"))
        self.label_3.setText(_translate("tabInfo", "Zone"))
        self.label_9.setText(_translate("tabInfo", "Resources"))
        self.label_6.setText(_translate("tabInfo", "iBridges Logfiles"))
