# Form implementation generated from reading ui file 'ibridgesgui/ui_files/tabSearch.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tabSearch(object):
    def setupUi(self, tabSearch):
        tabSearch.setObjectName("tabSearch")
        tabSearch.resize(1278, 763)
        tabSearch.setStyleSheet("QWidget\n"
"{\n"
"    background-color: rgb(211,211,211);\n"
"    color: rgb(88, 88, 90);\n"
"    selection-background-color: rgb(21, 165, 137);\n"
"    selection-color: rgb(245, 244, 244);\n"
"    font: 16pt\n"
"}\n"
"\n"
"QLabel#error_label\n"
"{\n"
"    color: rgb(220, 130, 30);\n"
"}\n"
"\n"
"QLineEdit, QTextEdit, QTableWidget\n"
"{\n"
"   background-color:  rgb(245, 244, 244)\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(21, 165, 137);\n"
"    color: rgb(245, 244, 244);\n"
"}\n"
"\n"
"QPushButton#home_button, QPushButton#parent_button, QPushButton#refresh_button\n"
"{\n"
"    background-color: rgb(245, 244, 244);\n"
"}\n"
"\n"
"QTabWidget#info_tabs\n"
"{\n"
"     background-color: background-color: rgb(211,211,211);\n"
"}\n"
"\n"
"")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(tabSearch)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 0, 1, 1)
        self.checksum_field = QtWidgets.QLineEdit(parent=tabSearch)
        self.checksum_field.setObjectName("checksum_field")
        self.gridLayout_2.addWidget(self.checksum_field, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=tabSearch)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.path_field = QtWidgets.QLineEdit(parent=tabSearch)
        self.path_field.setObjectName("path_field")
        self.gridLayout_2.addWidget(self.path_field, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=tabSearch)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=tabSearch)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.val3 = QtWidgets.QLineEdit(parent=tabSearch)
        self.val3.setObjectName("val3")
        self.gridLayout.addWidget(self.val3, 5, 1, 1, 1)
        self.key4 = QtWidgets.QLineEdit(parent=tabSearch)
        self.key4.setObjectName("key4")
        self.gridLayout.addWidget(self.key4, 6, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.val1 = QtWidgets.QLineEdit(parent=tabSearch)
        self.val1.setObjectName("val1")
        self.gridLayout.addWidget(self.val1, 3, 1, 1, 1)
        self.key2 = QtWidgets.QLineEdit(parent=tabSearch)
        self.key2.setObjectName("key2")
        self.gridLayout.addWidget(self.key2, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem3, 0, 0, 1, 1)
        self.val4 = QtWidgets.QLineEdit(parent=tabSearch)
        self.val4.setObjectName("val4")
        self.gridLayout.addWidget(self.val4, 6, 1, 1, 1)
        self.key1 = QtWidgets.QLineEdit(parent=tabSearch)
        self.key1.setObjectName("key1")
        self.gridLayout.addWidget(self.key1, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=tabSearch)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label1 = QtWidgets.QLabel(parent=tabSearch)
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 1, 0, 1, 1)
        self.key3 = QtWidgets.QLineEdit(parent=tabSearch)
        self.key3.setObjectName("key3")
        self.gridLayout.addWidget(self.key3, 5, 0, 1, 1)
        self.val2 = QtWidgets.QLineEdit(parent=tabSearch)
        self.val2.setObjectName("val2")
        self.gridLayout.addWidget(self.val2, 4, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem4, 7, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.search_button = QtWidgets.QPushButton(parent=tabSearch)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        self.search_button.setFont(font)
        self.search_button.setAutoDefault(False)
        self.search_button.setDefault(True)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_5.addWidget(self.search_button)
        self.clear_button = QtWidgets.QPushButton(parent=tabSearch)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        self.clear_button.setFont(font)
        self.clear_button.setStyleSheet("")
        self.clear_button.setObjectName("clear_button")
        self.horizontalLayout_5.addWidget(self.clear_button)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.download_button = QtWidgets.QPushButton(parent=tabSearch)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        self.download_button.setFont(font)
        self.download_button.setStyleSheet("")
        self.download_button.setObjectName("download_button")
        self.horizontalLayout_5.addWidget(self.download_button)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout.addItem(spacerItem6)
        self.error_label = QtWidgets.QLabel(parent=tabSearch)
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.verticalLayout.addWidget(self.error_label)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.info_label = QtWidgets.QLabel(parent=tabSearch)
        self.info_label.setObjectName("info_label")
        self.verticalLayout_3.addWidget(self.info_label)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.search_table = QtWidgets.QTableWidget(parent=tabSearch)
        self.search_table.setMinimumSize(QtCore.QSize(0, 200))
        self.search_table.setMaximumSize(QtCore.QSize(16777215, 500))
        self.search_table.setStyleSheet("")
        self.search_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.search_table.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.search_table.setAlternatingRowColors(False)
        self.search_table.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.search_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.search_table.setObjectName("search_table")
        self.search_table.setColumnCount(5)
        self.search_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setText("Type")
        self.search_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.search_table.setHorizontalHeaderItem(4, item)
        self.search_table.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_3.addWidget(self.search_table)

        self.retranslateUi(tabSearch)
        QtCore.QMetaObject.connectSlotsByName(tabSearch)

    def retranslateUi(self, tabSearch):
        _translate = QtCore.QCoreApplication.translate
        tabSearch.setWindowTitle(_translate("tabSearch", "Form"))
        self.label_3.setText(_translate("tabSearch", "Path"))
        self.label_5.setText(_translate("tabSearch", "Checksum"))
        self.label_6.setText(_translate("tabSearch", "Search Wildcard is: %"))
        self.label.setText(_translate("tabSearch", "Value (optional)"))
        self.label1.setText(_translate("tabSearch", "Metadata Key"))
        self.search_button.setText(_translate("tabSearch", "Search"))
        self.clear_button.setText(_translate("tabSearch", "Clear Results"))
        self.download_button.setText(_translate("tabSearch", "Download Selection"))
        self.info_label.setText(_translate("tabSearch", "Double-click to load to Browser tab"))
        self.search_table.setSortingEnabled(True)
        item = self.search_table.horizontalHeaderItem(1)
        item.setText(_translate("tabSearch", "Path"))
        item = self.search_table.horizontalHeaderItem(2)
        item.setText(_translate("tabSearch", "Size [bytes]"))
        item = self.search_table.horizontalHeaderItem(3)
        item.setText(_translate("tabSearch", "Created"))
        item = self.search_table.horizontalHeaderItem(4)
        item.setText(_translate("tabSearch", "Modified"))
