# Form implementation generated from reading ui file 'ibridgesgui/ui_files/uploadData.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_uploadData(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(936, 395)
        Form.setStyleSheet("QWidget\n"
"{\n"
"    background-color: rgb(211,211,211);\n"
"    color: rgb(88, 88, 90);\n"
"    selection-background-color: rgb(21, 165, 137);\n"
"    selection-color: rgb(245, 244, 244);\n"
"    font: 16pt\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"  background-color: rgb(21, 165, 137);\n"
"}\n"
"\n"
"QLabel#error_label\n"
"{\n"
"    color: rgb(220, 130, 30);\n"
"}\n"
"\n"
"QLineEdit, QTextEdit, QTableWidget\n"
"{\n"
"   background-color:  rgb(245, 244, 244)\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(21, 165, 137);\n"
"    color: rgb(245, 244, 244);\n"
"}\n"
"\n"
"QPushButton#home_button, QPushButton#parent_button, QPushButton#refresh_button\n"
"{\n"
"    background-color: rgb(245, 244, 244);\n"
"}\n"
"\n"
"QTabWidget#info_tabs\n"
"{\n"
"     background-color: background-color: rgb(211,211,211);\n"
"}\n"
"\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.destination_label = QtWidgets.QLabel(parent=Form)
        self.destination_label.setText("")
        self.destination_label.setObjectName("destination_label")
        self.gridLayout.addWidget(self.destination_label, 2, 2, 1, 1)
        self.overwrite = QtWidgets.QCheckBox(parent=Form)
        self.overwrite.setObjectName("overwrite")
        self.gridLayout.addWidget(self.overwrite, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 4, 1, 1)
        self.label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.folder_button = QtWidgets.QPushButton(parent=Form)
        self.folder_button.setObjectName("folder_button")
        self.horizontalLayout_3.addWidget(self.folder_button)
        self.file_button = QtWidgets.QPushButton(parent=Form)
        self.file_button.setObjectName("file_button")
        self.horizontalLayout_3.addWidget(self.file_button)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 2, 1, 1)
        self.error_label = QtWidgets.QLabel(parent=Form)
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.gridLayout.addWidget(self.error_label, 9, 0, 1, 6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.upload_button = QtWidgets.QPushButton(parent=Form)
        self.upload_button.setObjectName("upload_button")
        self.horizontalLayout.addWidget(self.upload_button)
        self.hide_button = QtWidgets.QPushButton(parent=Form)
        self.hide_button.setObjectName("hide_button")
        self.horizontalLayout.addWidget(self.hide_button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 2, 1, 1)
        self.sources_list = QtWidgets.QTextBrowser(parent=Form)
        self.sources_list.setObjectName("sources_list")
        self.gridLayout.addWidget(self.sources_list, 1, 2, 1, 1)
        self.progress_bar = QtWidgets.QProgressBar(parent=Form)
        self.progress_bar.setMaximum(100)
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setTextVisible(False)
        self.progress_bar.setObjectName("progress_bar")
        self.gridLayout.addWidget(self.progress_bar, 5, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Upload"))
        self.overwrite.setText(_translate("Form", "Overwrite existing data"))
        self.label_5.setText(_translate("Form", "Uploading to"))
        self.label.setText(_translate("Form", "Upload data"))
        self.label_2.setText(_translate("Form", "Options:"))
        self.folder_button.setText(_translate("Form", "Select Folders"))
        self.file_button.setText(_translate("Form", "Select Files"))
        self.upload_button.setText(_translate("Form", "Upload"))
        self.hide_button.setText(_translate("Form", "Close Window"))
